# Generated by Django 2.1 on 2018-08-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=30, unique=True)),
                ('url', models.URLField()),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
